// src/react/App.js
import React from 'react';

// Styles
import './App.css';

// Components
import Card from './components/Card.js';

// Data
import exampleData from '../_shared/data/example/card--item.json';

class App extends React.Component {
	render(){
		return (
			<React.Fragment>
				<p id="intro" className="c-intro">Create a custom card for an imaginary trading card game.</p>

				<Card id="card" {...exampleData} />
			</React.Fragment>
		);
	}
}

export default App;

// src/angular/src/app/app.component.ts
// Components
import { Component, ViewEncapsulation } from '@angular/core';

// Data
import exampleData from '../../../_shared/data/example/card--item.json';

@Component({
  selector: '#app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
	exampleData: object = exampleData;
}

<p id="intro" className="c-intro">Create a custom card for an imaginary trading card game.</p>

<card id="card" [identity]="identity" [attributes]="attributes"></card>

<fieldset>
	<legend><samp>app.component.html</samp></legend>
	<dl>
		<dt>Identity</dt>
		<dd><pre><samp>{{ identity | json }}</samp></pre></dd>

		<dt>Attributes</dt>
		<dd><pre><samp>{{ attributes | json }}</samp></pre></dd>
	</dl>
</fieldset>
